pragma solidity ^0.4.24;
               
//MMMMMMMMMMMMMMMWXKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXW      
//MMMMMMMMMMMMMWXKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKXW              
//MMMMMMMMMMMWXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKNW            
//MMMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMWX0xoc:;,''''',;clxKNMMMMMMMMMMMMMMMMMMMMMMMMMNKKN           
//MMMMMMMMWXKNMMMMMMMMMMMMMMMMMMMMMMMWXkl:'..................;dKWMMMMMMMMMMMMMMMMMMMMMMMWXKXW         
//MMMMMMMNKKWMMMMMMMMMMMMMMMMMMMMMMW0l'.........................l0WMMMMMMMMMMMMMMMMMMMMMMMWKKN        
//MMMMMMX0XWMMMMMMMMMMMMMMMMMMMMMMXo.............................'dNMMMMMMMMMMMMMMMMMMMMMMMWX0N       
//MMMMWXKNMMMMMMMMMMMMMMMMMMMMMMMNl.....''.........................oNMMMMMMMMMMMMMMMMMMMMMMMMX0X      
//MMMWXKNMMMMMMMMMMMMMMMMMMMMMMMM0, .,oOKK0kl,...........';:lolc,..xWMMMMMMMMMMMMMMMMMMMMMMMMN0X
//MMMXKNMMMMMMMMMMMMMMMMMMMMMMMMMO''dKNNNNNNNKkl;;;:cldxOKXNNNNNXkl.'OMMMMMMMMMMMMMMMMMMMMMMMMMN0X 
//MMN0XMMMMMMMMMMMMMMMMMMMMMMMMMWx,dNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNXl,OMMMMMMMMMMMMMMMMMMMMMMMMMMX0N 
//MWKXMMMMMMMMMMMMMMMMMMMMMMMMMMWo,kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXc;0MMMMMMMMMMMMMMMMMMMMMMMMMMWKKW 
//MXKWMMMMMMMMMMMMMMMMMMMMMMMMMMNc;ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMN0X 
//NKXMMMMMMMMMMMMMMMMMMMMMMMMMMMX:;0NXOxolllodk0XNNNNNNNKOxolllodxOl,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0W 
//XKWMMMMMMMMMMMMMMMMMMMMMMMMMMWO;;xl,...'''....;o0NNXkc'...'''......cXMMMMMMMMMMMMMMMMMMMMMMMMMMMN0X 
//KKMMMMMMMMMMMMMMMMMMMMMMMMMMKl:,...,:c:;;;;:c:'.'lxc..';;;;;:lol:'..:OWMMMMMMMMMMMMMMMMMMMMMMMMMMKKW
//0XMMMMMMMMMMMMMMMMMMMMMMMMMWx,ol..:dl,.    .;oo;.   .:c.     .cddo;  'OMMMMMMMMMMMMMMMMMMMMMMMMMMX0N
//0NMMMMMMMMMMMMMMMMMMMMMMMMMWd,oc .ldoc;''',;lddc.   .;l:,''',:oddl,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMN0N
//KWMMMMMMMMMMMMMMMMMMMMMMMMMWd,xk'.,ldddddddddoc' .;;...;cllooll:;..,;'xWMMMMMMMMMMMMMMMMMMMMMMMMMNKN
//KWMMMMMMMMMMMMMMMMMMMMMMMMMWx,dXO:..';:cllc:;.. .oKXk' .........,cxKd,xMMMMMMMMMMMMMMMMMMMMMMMMMMWKN
//KNMMMMMMMMMMMMMMMMMMMMMMMMMMXd;cxOOo:,'....',:;.,x0Okc.;kOxxxkO0XNNNx,oWMMMMMMMMMMMMMMMMMMMMMMMMMNKN
//0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,lKNNXK0OO0KXXk::lllllokXNNNNNNNN0occckWMMMMMMMMMMMMMMMMMMMMMMMMMX0N
//0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,xNNNNNNNNNNNNXXNNNNNNXxo0NNNNNKc,xXNMMMMMMMMMMMMMMMMMMMMMMMMMMMX0W
//KKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;kNNNNNNNNNXXNNNNNNXXO;:0NNNNXd,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKK 
//XKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,;ONNNNXklllllllllllc:ckNNNNNx'.xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0N  
//WKKMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,  ,kNNNNK000000000000KXNNNNXx'  .l0WMMMMMMMMMMMMMMMMMMMMMMMMMWKKW
//MN0NMMMMMMMMMMMMMMMMMMMMMMMMNOc.    .,oKNNNNNNNNNNNNNNNNNNNNKo'.    .oKWMMMMMMMMMMMMMMMMMMMMMMMX0N 
//MWKKWMMMMMMMMMMMMMMMMMMMMMNk;.  .:c',:,;dKNNNNNNNNNNNNNNNNKx;,;';d;   'kWMMMMMMMMMMMMMMMMMMMMMW0K   
//MMWKKWMMMMMMMMMMMMMMMMMMMMX:    .,;.;ddc,;lx0XNNNNNNNNX0kl;,cdo';d:.   cXMMMMMMMMMMMMMMMMMMMMWKKW   
//MMMNKXWMMMMMMMMMMMMMMMMMMMWKxc;..   ;dxxxo:;;:cllllllc:;;:ldxxl.    .;dKWMMMMMMMMMMMMMMMMMMMWKKW    
//MMMMNKXWMMMMMMMMMMMMMMMMMMMMMMWX0xc.,dxxxxxxdolcccccclodxxxxxxl. .;d0NMMMMMMMMMMMMMMMMMMMMMWKKW     
//MMMMMNKKWMMMMMMMMMMMMMMMMMMMMMMMMMK:';;,,,,,,,;;;;;;;;;;;;;;::,.lKWMMMMMMMMMMMMMMMMMMMMMMMWKKW      
//MMMMMMWKKNMMMMMMMMMMMMMMMMMMMMMMMMWX0d'                     .:dkXMMMMMMMMMMMMMMMMMMMMMMMMN0KW       
//MMMMMMMWXKXWMMMMMMMMMMMMMMMMMMMMMMMWO;                       'kWMMMMMMMMMMMMMMMMMMMMMMMWX0XW        
//MMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMKc.',,.               .,'..'kWMMMMMMMMMMMMMMMMMMMMMNKKN          
//MMMMMMMMMMWXKXWMMMMMMMMMMMMMMMMMMMMWXXNN0c;:clodxxxxol:;,:0NK0OKWMMMMMMMMMMMMMMMMMMMNKKXW           
//MMMMMMMMMMMMWXKXWMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMNKKXW             
//MMMMMMMMMMMMMMWXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXW               
//MMMMMMMMMMMMMMMMWNKKXWMMMMMMMMMMMMMM     www.apelslab.com   MMMMMMMMMMMMMMMMMNXKKNW                 
//MMMMMMMMMMMMMMMMMMMNXKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKXW                    
//MMMMMMMMMMMMMMMMMMMMMMNXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKXN                       
//MMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXKXXNW                          


   